from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .cmu_nodes import NODE_CLASS_MAPPINGS as CMU_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as CMU_NAMES

NODE_CLASS_MAPPINGS.update(CMU_CLASSES)
NODE_DISPLAY_NAME_MAPPINGS.update(CMU_NAMES)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']