from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .cmu_nodes import NODE_CLASS_MAPPINGS as CMU_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as CMU_NAMES
from .fbx_nodes import NODE_CLASS_MAPPINGS as FBX_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as FBX_NAMES

NODE_CLASS_MAPPINGS.update(CMU_CLASSES)
NODE_DISPLAY_NAME_MAPPINGS.update(CMU_NAMES)

NODE_CLASS_MAPPINGS.update(FBX_CLASSES)
NODE_DISPLAY_NAME_MAPPINGS.update(FBX_NAMES)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
